test against the future NodeJS LTS version
mocha was updated to the latest version, because we were getting issue
with yargs and node 26.

```
const {applyExtends, cjsPlatformShim, Parser, Yargs, processArgv} = require('./build/index.cjs')
                                                                    ^
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///home/runner/work/suitest-js-api/suitest-js-api/node_modules/mocha/node_modules/yargs/yargs:3:69
```